### ISSUE TITLE
t-SNE visualization

### ISSUE THREAD

**Issue by Zeyu1226-mt** [dk-kim/DFWSGAR#11]
Hello, very meaningful work. How to draw this t-SNE visualization? Could you please share the visualization method or reference code? My email is 1049566058@qq.com. Thank you very much.

**Comment by dk-kim** [comment]
Hi, we just use scikit-learn library t-SNE method (sklearn.manifold.TSNE). You can easily find many examples using this library.

**Comment by Zeyu1226-mt** [comment]
Thanks very much🤝🙏



发自我的iPhone


------------------ Original ------------------
From: Dongkeun Kim ***@***.***&gt;
Date: Thu,Apr 13,2023 1:03 PM
To: dk-kim/DFWSGAR ***@***.***&gt;
Cc: 习泽宇 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dk-kim/DFWSGAR] t-SNE visualization (Issue #11)





 
Hi, we just use scikit-learn library t-SNE method (sklearn.manifold.TSNE). You can easily find many examples using this library.

**Comment by Xiyu-AI** [comment]
Sorry to bother you. I still haven't drawn a visualization of TSNE. Can you share your code? Thank you 🙏



发自我的iPhone


------------------ Original ------------------
From: Dongkeun Kim ***@***.***&gt;
Date: Thu,Apr 13,2023 1:03 PM
To: dk-kim/DFWSGAR ***@***.***&gt;
Cc: 习泽宇 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dk-kim/DFWSGAR] t-SNE visualization (Issue #11)





 
Hi, we just use scikit-learn library t-SNE method (sklearn.manifold.TSNE). You can easily find many examples using this library.
