### ISSUE TITLE
How to calculate FLOPs in the paper.

### ISSUE THREAD

**Issue by P-DX** [dk-kim/DFWSGAR#13]
Hi, thank you for your attention. 
We utilize ptflops for calculating FLOPs. 
If you set the input as [1, 18, 3, 1280, 720], all FLOPs values for our model and other baselines should be 4 times. 
If you have any further problem, please let me know.

_Originally posted by @dk-kim in https://github.com/dk-kim/DFWSGAR/issues/5#issuecomment-1273321166_

**Comment by P-DX** [comment]
> ```
>           Hi, thank you for your attention. 
> ```
> 
> We utilize ptflops for calculating FLOPs. If you set the input as [1, 18, 3, 1280, 720], all FLOPs values for our model and other baselines should be 4 times. If you have any further problem, please let me know.
> 
> _Originally posted by @dk-kim in [#5 (comment)](https://github.com/dk-kim/DFWSGAR/issues/5#issuecomment-1273321166)_

Thanks very much for the work you proposed and the thoughts you shared.
I would like to figure out the exact calculation of FLOPs in your paper, such as the input size used to calculate the FLOPs, how it is calculated, etc.
Also you mentioned that if we use [1, 18, 3, 1280, 720] as input, we will get 4 times the result of FLOPs, so what input size should be used to calculate the FLOPs result. Thank you for your reply.

**Comment by dk-kim** [comment]
As mention in #5, we use ptflops for calculating FLOP. 
I remember that we use [1, 18, 3, 720, 1280] as the input for FLOP calculation, but upon checking the results, it seems there are mistakes in the paper. 
When this input is used, the result is four times the FLOPs for all baselines and our model. Therefore, if you want to cite FLOP calculation result of our paper, we recommend multiplying the FLOPs value by four for all models.

**Comment by P-DX** [comment]
> As mention in #5, we use ptflops for calculating FLOP. I remember that we use [1, 18, 3, 720, 1280] as the input for FLOP calculation, but upon checking the results, it seems there are mistakes in the paper. When this input is used, the result is four times the FLOPs for all baselines and our model. Therefore, if you want to cite FLOP calculation result of our paper, we recommend multiplying the FLOPs value by four for all models.

Thanks a lot!!!
