### ISSUE TITLE
Question about missing module 

### ISSUE THREAD

**Issue by LUJUNYIhhh** [dk-kim/DFWSGAR#2]
Hi, while runing test scripts on volleyball dataset,  I get an error information in ./module/backbone.py, just like:
```
 from spatial_correlation_sampler import SpatialCorrelationSampler 
ModuleNotFoundError: No module named 'spatial_correlation_sampler' .
```
 I have searched spatial_correlation_sampler in the folder but didn't find any function about it. Could you tell me how to solve it? Thanks a lot.

**Comment by dk-kim** [comment]
Hi, do you install additional package mentioned on readme?
If you execute script (scripts/setup.sh), SpatialCorrelationSampler might be installed. 
Or you can install directly from the original implementation (https://github.com/ClementPinard/Pytorch-Correlation-extension).

**Comment by LUJUNYIhhh** [comment]
Thanks, I have solved it by "pip install spatial-correlation-sampler".
