### ISSUE TITLE
FLOPs in the paper

### ISSUE THREAD

**Issue by Meta-AI-learner** [dk-kim/DFWSGAR#5]
Hi, thanks for your great work!
I want to know how you calculate the FLOPs in your paper, when i set the input as [1,18,3,1280,720], i got a much higher FLOPs than yours.  Could you give any advice on this problem?

Thank you very much!
Best regards.

**Comment by dk-kim** [comment]
Hi, thank you for your attention. 
We utilize ptflops for calculating FLOPs. 
If you set the input as [1, 18, 3, 1280, 720], all FLOPs values for our model and other baselines should be 4 times. 
If you have any further problem, please let me know.

**Comment by Meta-AI-learner** [comment]
Thanks for your fast response.  If it is possible I would like to know the number of frames and the input size you used when calculating FLOPs. When i set input as [1,18,3,720,1280], i got 608G FLOPs, which is nearly 2 times. Did you set input as [1,9,3,720,1280] in your paper, i.e., 9 frames?

Thank you very much!

**Comment by dk-kim** [comment]
You mean 608GMac? I set input as [1, 18, 3, 720, 1280] for our model, we get 1254G Flops.

**Comment by Meta-AI-learner** [comment]
Sorry, i made mistake. it was GMAC. I used thop for calculation.

Thanks for your response.

**Comment by P-DX** [comment]
> Sorry, i made mistake. it was GMAC. I used thop for calculation.
> 
> Thanks for your response.

Thanks for the question, I'm having a similar problem.
I would like to ask you how you corrected the gap between the FLOPs in the paper and the actual doubled FLOPs calculated.
Which code was ultimately used for the calculation.
