### ISSUE TITLE
Question about Volleyball.

### ISSUE THREAD

**Issue by LemonQC** [dk-kim/DFWSGAR#8]
In your paper, you said you replace the ground-truth bounding boxes with an object detector in the weakly-supervised setting. However, whether you should do this in detector-free mode?

**Comment by dk-kim** [comment]
No, we do not utilize bounding boxes produced by the off-the-shelf object detector for our model (detector-free mode). 
We use bounding boxes produced by object detector only for other GAR methods since this methods need to extract actor features from the image feature maps by applying RoI Align.

**Comment by LemonQC** [comment]
> No, we do not utilize bounding boxes produced by the off-the-shelf object detector for our model (detector-free mode). We use bounding boxes produced by object detector only for other GAR methods since this methods need to extract actor features from the image feature maps by applying RoI Align.

I see, I misunderstand your words. Thanks for your answer.
