### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Zeyu1226-mt** [dk-kim/DFWSGAR#9]
![2023-02-17 19-39-26 的屏幕截图](https://user-images.githubusercontent.com/57516993/219644626-223fe282-5822-4c7a-9525-0073a09c87c7.png)
This problem is encountered when running train.py. Please tell me how to solve it, thank you

**Comment by dk-kim** [comment]
We are hard to figure out your situation. Could you give me more information? 
If you aren't using our training script, you may check num_activities argument.
